### ISSUE TITLE
Nekoslife returns 'null' 

### ISSUE THREAD

**Issue by Therealloli101** [scrazzz/AliucordPlugins#10]
Every time I try to use the nekoslife plugin it just returns 'null' i tried re-installing but didn't help

**Comment by scrazzz** [comment]
@Therealloli101 send a screenshot

**Comment by scrazzz** [comment]
Or join this server: https://discord.gg/tdjBfsvhHT and I'll help you out

**Comment by scrazzz** [comment]
Ok I've found out the issue, I need to check the API and see why it returns "null". They probably stopped serving nsfw contents through the API or something idk.

**Comment by Therealloli101** [comment]
> Ok I've found out the issue, I need to check the API and see why it returns "null". They probably stopped serving nsfw contents through the API or something idk. 

Nope, i used a self bot on a test account and the self bot was able to get nsfw images from the API

**Comment by scrazzz** [comment]
> Nope, i used a self bot on a test account and the self bot was able to get nsfw images from the API

Uh ok. I still haven't looked into this. I'm not motivated to work on this so yeah.

**Comment by scrazzz** [comment]
Ok, I've looked into this. The reason why it says `null` is because the response which is serialized using `class Result(val url: String)` can't find `url` so it returns `null` instead.

If you go to the NSFW endpoints (https://nekos.life/api/v2/img/boobs), you can see it returns: `{"msg":"404"}`. I have only tested 2 NSFW endpoints and this is what I get.

I can't really do anything here since it's not under my control.

**Comment by Quinten0508** [comment]
Looking at all the endpoints (https://nekos.life/api/v2/endpoints) it does seem like NSFW endpoints have been removed. However, one could update the list of categories displayed within the slash command to this new list:
```
<'smug', 'woof', 'gasm', '8ball', 'goose', 'cuddle', 'avatar', 'slap', 'v3', 'pat', 'gecg', 'feed', 'fox_girl', 'lizard', 'neko', 'hug', 'meow', 'kiss', 'wallpaper', 'tickle', 'spank', 'waifu', 'lewd', 'ngif'>
```

I confirmed that these entries do give an actual output, it's just that you have to fill them in manually.

It also seems like nekos.life decided to completely remove NSFW content, I cannot find a reference to it anywhere. On the other hand, there are no mentions of its disappearance ¯\_(ツ)_/¯

**Comment by scrazzz** [comment]
There's a new domain now, I don't exactly remember what it is.

**Comment by scrazzz** [comment]
> They removed all of the NSFW endpoints because cf flagged everything as CP
lmao

**Comment by Quinten0508** [comment]
> They removed all of the NSFW endpoints because cf flagged everything as CP

Huh, I've never seen cp when using their api. Can imagine some must've sneaked in tho lmao. Also probably stupid question but who is cf?

**Comment by scrazzz** [comment]
> Huh, I've never seen cp when using their api. Can imagine some must've sneaked in tho lmao. Also probably stupid question but who is cf?

Cloudfare
