### ISSUE TITLE
Makesweet

### ISSUE THREAD

**Issue by ChunkyCookie88** [scrazzz/AliucordPlugins#11]
I don't know how to use this ![Screenshot_20220507-121810.jpg](https://user-images.githubusercontent.com/37356588/167263044-07ee36ca-fb4e-4a7e-88a4-b3c2bef041d4.jpg)

**Comment by scrazzz** [comment]
It won't work in that channel because Aliucord slash commands breaks when you use it in channelz were you don't have "Use slash command" perms. Try this command in #bot-spam channel or in your private server.
