### ISSUE TITLE
What's going on with makesweet? 

### ISSUE THREAD

**Issue by jay5656** [scrazzz/AliucordPlugins#9]
Site (https://mkswt.herokuapp.com/) says to message you on discord but, the link in your bio makes me think maybe your account was hacked? So kinda worried to message you on discord

**Comment by scrazzz** [comment]
Bruh moment.

My account is not hacked. The link on my bio is just a clone of my GitHub pages site: https://scrazzz.github.io/
I just own a `d1scord.me` domain for fun which is used instead of `scrazzz.github.io`

:trollface:

**Comment by scrazzz** [comment]
https://scrazzz.github.io/
https://d1scord.me/

Same thing
